### ISSUE TITLE
Support configurable max line size

### ISSUE THREAD

**Issue by Zajozor** [Scout24/stdin-rotate#3]
By default, go's Scanner has a pretty strict buffer length.
Accepting a command line option would be wonderful.

We could do something like mentioned here:
https://stackoverflow.com/questions/39859222/golang-how-to-overcome-scan-buffer-limit-from-bufio
and here
https://stackoverflow.com/questions/21124327/how-to-read-a-text-file-line-by-line-in-go-when-some-lines-are-long-enough-to-ca

**Comment by Zajozor** [comment]
I can make a PR for this if you are interested and willing to merge :)

**Comment by deigote** [comment]
Hey @Zajozor thanks! We are more than willing to merge, thanks in advance 👍!
